### ISSUE TITLE
About where the  Neighbor Iou-voting Strategy 

### ISSUE THREAD

**Issue by deeplearningnewbi** [Say2L/NIV-SSD#1]
May I ask where the Neighbor ou-voting Strategy part is, it does not seem to be in the code.

**Comment by Say2L** [comment]
> May I ask where the Neighbor ou-voting Strategy part is, it does not seem to be in the code.

It is employed in the file dcdet/detectors/second_cia_iou.py. And the code of NIV is included in the file pcdet/ops/iou3d_nms/iou3d_nms_utils.py. The function of NIV is niv_nms_gpu.

**Comment by deeplearningnewbi** [comment]
> > May I ask where the Neighbor ou-voting Strategy part is, it does not seem to be in the code.
> 
> It is employed in the file dcdet/detectors/second_cia_iou.py. And the code of NIV is included in the file pcdet/ops/iou3d_nms/iou3d_nms_utils.py. The function of NIV is niv_nms_gpu.

Thanks for answering my questions. Thank you!
